name: AboutMe

on: [push]

jobs:
  build4test:
    runs-on: ubuntu-latest

    steps:
    - name: Install sphinx
      run : sudo apt install sphinx
    - name: select folder
      run : pwd && ls -la 
    - name: cloning repository
      run : git clone https://github.com/Mitya178/test2github.git
    - name: check my position
      run : pwd && ls -la
    - name: change permission
      run : sudo chmod 777 test2github
    - name: inside myfutureREP
      run : cd test2github && ls -la && pwd &&mkdir dima && ls -la && pwd
    - name: make html
      run : sphinx-build -b html /home/runner/work/test2github/test2github/test2github /home/runner/work/test2github/test2github/test2github/dima && ls -la
    - name: coping
      run : cd _build && ls -la && cd html && ls -la
